//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoriesManager.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestsModelContainer : DbContext
    {
        public TestsModelContainer()
            : base("name=TestsModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TestSource> TestSources { get; set; }
        public virtual DbSet<TestReport> TestReports { get; set; }
        public virtual DbSet<TestRunResult> TestRunResults { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
