//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoriesManager.Model
{
    using System;
    
    public enum ReportStatus : short
    {
        Created = 0,
        Processing = 1,
        Closed = 2,
        Error = 3
    }
}
