//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoriesManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestReport()
        {
            this.TestRunResults = new HashSet<TestRunResult>();
        }
    
        public string Name { get; set; }
        public int Id { get; set; }
        public ReportStatus Status { get; set; }
        public int LastRunResultId { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual TestSource TestSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestRunResult> TestRunResults { get; set; }
    }
}
